### ISSUE TITLE
Button Hover

### ISSUE THREAD

**Issue by rifajri** [raymondtju/schoolabs#2]
button hovernya masih white
![image](https://github.com/raymondtju/schoolabs/assets/130887569/c5173907-779a-4174-82b2-b8a878248b59)

**Comment by Jayennn** [comment]
[](https://github.com/raymondtju/schoolabs/tree/35703f8a8fd57fbff4a9d88066e3873cc6eeadff)

**Comment by Jayennn** [comment]
fix: button [](https://github.com/raymondtju/schoolabs/tree/35703f8a8fd57fbff4a9d88066e3873cc6eeadff)

**Comment by Jayennn** [comment]
fix button [commit](https://github.com/raymondtju/schoolabs/tree/35703f8a8fd57fbff4a9d88066e3873cc6eeadff)
