### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by rifajri** [raymondtju/schoolabs#3]
![image](https://github.com/raymondtju/schoolabs/assets/130887569/a03f51ee-f2d2-4125-8eea-0f31526a2412)

**Comment by rifajri** [comment]
Navabar pada saat di scroll kebawah sticky

**Comment by raymondtju** [comment]
done making the navbar sticky  at commit https://github.com/raymondtju/schoolabs/commit/fa38582294f2aeac3bdfab41773d496b550dcee1
