### ISSUE TITLE
arrow filter terbalik

### ISSUE THREAD

**Issue by donyalhadi** [raymondtju/schoolabs#8]
![image](https://github.com/raymondtju/schoolabs/assets/145916099/96102c29-53b1-491a-9b19-7d85e01dd244)
arrownya kebalik ya saat hide, begitu juga saat expand

**Comment by rifajri** [comment]
![image](https://github.com/raymondtju/schoolabs/assets/130887569/fbed6eac-cd87-4974-b443-b22a5c0a5862)

**Comment by rifajri** [comment]
![image](https://github.com/raymondtju/schoolabs/assets/130887569/e91636f7-ed50-4730-8c07-55b5e9d3aa38)

**Comment by raymondtju** [comment]
done
